apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: httpd
    owenr: wojciech
  name: cluster-can-west
  namespace: simple-app
spec:
  clusterSelector:
    matchLabels:
      env: west 
